#!/bin/bash

# Parse arguments
if [ "$#" -eq 0 ]; then # Case do all tests
  for testsrcfile in *_test.cpp ; do
    ./test $(basename $testsrcfile .cpp)
    echo ""
  done
  exit
elif [ "$#" -eq 1 ]; then # Case do all tests for given executable
  getnum="find . -type f -name '$1_out_*' | wc -l"
  numbers=$(eval $getnum)
  numbers=$(seq $numbers)
elif [ "$#" -ge 2 ]; then # Case do specific test
  numbers=$2
else # Case incorrect input
  echo "Invalid input, exiting."
  exit 1
fi

name=$1 
program="./../build/${name}"
temp=.tempfile

echo "Unit Test $1 (left=expected, right=produced)"
echo ""

for i in $numbers
do
  inputname="${name}_in_${i}"
  outputname="${name}_out_${i}"
  input=$(cat ${inputname})
  #output=$(cat ${outputname})
  #realoutput=$(${program} ${input})
  ${program} ${input} > ${temp}
  output=$(diff -q $outputname ${temp})
  
  # A third argument indicates we want the undiff'ed program output:
  if [[ -n "$3" ]] ; then
    echo " - INPUT:"
    echo ${input}
    echo ""
    echo "OUTPUT:"
    cat ${temp}
    continue
  fi

  echo -n "Test No. $i"
  if [[ ${output} = "" ]] ; then
    echo " - PASS"
  else
    echo " - FAIL"
    diff -y $outputname ${temp}
  fi
done

